[package]
name = "rust_ffi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "staticlib", "cdylib"]


[dependencies]
flutter_rust_bridge = "1.77.1"

[build-dependencies]
flutter_rust_bridge_codegen = "1.77.1"
